[package]
name = "n_body"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotters = "0.3.4"
nalgebra = "0.31.1"
fastrand = "1.8.0"
